server:
  port: 8888
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learning
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:

        format_sql: true
  ai:
    vertex:
      ai:
        project-id: gen-lang-client-0486578479
        location: asia-southeast1
        api-key: ${GEMINI_API_KEY}

        gemini:
          chat:
            options:
              model: gemini-1.5-flash
              temperature: 0.5
          embedding:
            options:
              model: text-embedding-004

    vectorstore:
      chroma:
        client:
          host: http://localhost
          port: 8000
        collection:
          name: "ai_tutor_collection"

application:
  storage:
    local-path: "./ai_tutor_documents"

